<script setup>
import { Cards, FormFields, Loader, RenderCards } from "@/components";
import { ref } from "@vue/reactivity";
import { onMounted, watch } from "@vue/runtime-core";

const loading = ref(false);
let posts = ref([]);

const searchText = ref("");

const fetchPost = async () => {
  loading.value = true;
  try {
    const response = await fetch("http://localhost:8081/api/v1/post", {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
      },
    });

    if (response.ok) {
      const result = await response.json();
      posts.value = result.data.reverse();
    }
  } catch (error) {
    alert("Something went wrong");
    console.log(error);
  } finally {
    loading.value = false;
  }
};

onMounted(() => {
  fetchPost();
});
</script>

<template>
  <section class="max-w-7xl mx-auto">
    <div>
      <h1 class="font-extrabold text-[#222328] text-[32px]">
        The Community Showcase
      </h1>
      <p class="mt-2 text-[#666e75] text-[14px] max-w-[500px]">
        Browse through a collection of imaginative and visually stunning images
        generated by DALL-E AI
      </p>
    </div>
    
    <div class="mt-10">
      <div v-if="loading" class="flex justify-center items-center">
        <Loader />
      </div>
      <div v-else>
        <div>
          <RenderCards :data="posts" title="No post found" />
        </div>
      </div>
    </div>
  </section>
</template>
